### ISSUE TITLE
Ruby files, strings and comments

### ISSUE THREAD

**Issue by prrrnd** [jeffschuil/oceanic-reef-syntax#1]
Hi, and thanks for the nice theme!
Would it be possible to do something about this?
![](http://i.imgur.com/6WN4Dvy.png)

**Comment by jeffschuil** [comment]
Thanks! Glad you like it. I updated string interpolation to this:
![photochute - atom 2015-05-20 11-55-43](https://cloud.githubusercontent.com/assets/146541/7733913/433de19e-fee7-11e4-9dc8-8b8949a0f5b4.png)

**Comment by prrrnd** [comment]
Thanks! :+1:
