### ISSUE TITLE
Deprecated selector in oceanic-reef-syntax

### ISSUE THREAD

**Issue by jaredmoody** [jeffschuil/oceanic-reef-syntax#4]
> oceanic-reef-syntax/index.less
> Starting from Atom v1.13.0, the contents of atom-text-editor elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using :host and ::shadow pseudo-selectors, and prepend all your syntax selectors with syntax--. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

**Comment by jeffschuil** [comment]
Stylesheet selectors were updated in PR #5. Thanks @bronson!
